<?php

namespace Database\Seeders;

use App\Office;
use Illuminate\Database\Seeder;

class OfficesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Office::create([
            'country' => 'Nigeria',
            'city' => 'Abuja',
            'key' => '',
            'flag' => '',
            'address' => 'No.5 Onitsha Crescent, Off Gimbiya Street, Area 11, Garki, Abuja',
            'email' => 'infoabuja@oisservices.com',
            'phone' => '+2348174477018',
            'working_time' => '8:30 am -  4:30 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Netherlands',
            'city' => 'The Hague',
            'key' => 'THE_HAGUE',
            'flag' => 'Netherlands.svg',
            'address' => 'First Floor, Regus Building, Koningin Juliana Plein 10. Postcode 2595AA, The Hague Central station,',
            'email' => 'infothehague@oisservices.com',
            'phone' => '0031708915324 - 0031687382130',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Turkey',
            'city' => 'Ankara',
            'key' => 'ANKARA',
            'flag' => 'Turkey.svg',
            'address' => 'Buyukesat Mahallesi, Ugur Mumcu\'nun Sokagi, Konak Apartmani, No:49/3 CANKAYA/ANKARA',
            'email' => 'infoankara@oisservices.com',
            'phone' => '00903124382175 - 00903124382176',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'USA',
            'city' => 'Atlanta',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => 'OIS Atlanta. GA, 918 Holcomb Bridge Road, Suite 204, Roswell, Atlanta, GA 30076',
            'email' => 'infoatlanta@oisservices.com',
            'phone' => '+1 404-695-6373',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'China',
            'city' => 'Beijing',
            'key' => 'BEIJING',
            'flag' => 'China.svg',
            'address' => 'Suite 908, Building B Kunsha Centre, No. 16 Xin Yuan Li Street, Chaoyang District, Beijing.',
            'email' => 'infobeijing@oisservices.com',
            'phone' => '+010-84004549',
            'working_time' => '9:00 am -  4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Lebanon',
            'city' => 'Beirut',
            'key' => 'BEIRUT',
            'flag' => 'Lebanon.svg',
            'address' => 'OIS Services, Beirut, Lebanon Jnah-Beirut Opposite Rafik Hariri University Hospital Mais 6',
            'email' => 'infobeirut@oisservices.com',
            'phone' => '009611845138',
            'working_time' => '9:00 am -  4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Egypt',
            'city' => 'Cairo',
            'key' => 'CAIRO',
            'flag' => 'Egypt.svg',
            'address' => '   2ND FLOOR AT 51-ELNOOR ST, ELDOKI, GIZA, EGYPT.',
            'email' => 'infocairo@oisservices.com',
            'phone' => '+20 237627293 - +20 237627294',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'SUNDAYS - THURSDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'South Africa',
            'city' => 'Cape Town',
            'key' => '',
            'flag' => 'SouthAfrica.svg',
            'address' => 'No 50, Long Street, Cape Town.',
            'email' => 'infocpt@oisservices.com',
            'phone' => '+27 210133161',
            'working_time' => '9:00 am - 12:00 pm & 1:00 pm - 4:30 pm',
            'working_days' => 'MONDAYS - WEDNESSDAY - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'USA',
            'city' => 'Chicago',
            'key' => 'CHICAGO',
            'flag' => 'USA.svg',
            'address' => '4001 West Devon, Suite 509. Chicago IL 60646 ',
            'email' => 'Infochicago@oisservices.com',
            'phone' => '+1 (773) 733-4600',
            'working_time' => 'N.A',
            'working_days' => 'N.A',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'UAE',
            'city' => 'Dubai',
            'key' => 'DUBAI',
            'flag' => 'UAE.svg',
            'address' => '22A (22nd floor), Silver Tower, Cluster I, Jumeirah Lake Towers, Dubai, U.A.E',
            'email' => 'infodubai@oisservices.com',
            'phone' => '+971 4 276 5448',
            'working_time' => '9:00 am -  3:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'China',
            'city' => 'Guangzhou',
            'key' => 'GUANGZHOU',
            'flag' => 'China.svg',
            'address' => 'Room 8E, 8th floor, Wingkin Square, No.29 Jianshe6malu, Yuexiu District, Guangzhou.',
            'email' => 'infoguangzhou@oisservices.com',
            'phone' => '+8620-37812021',
            'working_time' => '9:00 am -  4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'USA',
            'city' => 'Houston',
            'key' => 'Houston',
            'flag' => 'USA.svg',
            'address' => 'OIS Services, 9894 Bissonnet Street, Suite 745 Houston TX 77036.',
            'email' => 'infohouston@oisservices.com',
            'phone' => '+1 713 771 1871',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'South Africa',
            'city' => 'Johannesburg',
            'key' => 'JOHANNESBURG',
            'flag' => 'SouthAfrica.svg',
            'address' => '6 Bolton Road Parkwood Rosebank, 2193, Johannesburg, South Africa',
            'email' => 'infojoburg@oisservices.com',
            'phone' => '+27112682376, +27112682470',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 4:30 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'UK',
            'city' => 'London',
            'key' => 'LONDON',
            'flag' => 'UK.svg',
            'address' => '56-57 Fleet Street, London, EC4Y 1JU',
            'email' => 'info@oisservices.com',
            'phone' => '02078320000',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'USA',
            'city' => 'Los Angeles',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => 'OIS Los Angeles 5757 W. Century Boulevard, 90045 Los Angeles, California.',
            'email' => 'infola@oisservices.com',
            'phone' => '+1 301231 7000',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Spain',
            'city' => 'Madrid',
            'key' => '',
            'flag' => '',
            'address' => 'C.de Maudes, 62. 28003, Madrid',
            'email' => 'infomadrid@oisservices.com',
            'phone' => '+442078320014',
            'working_time' => 'N.A',
            'working_days' => 'N.A',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'India',
            'city' => 'Mumbai',
            'key' => 'MUMBAI',
            'flag' => 'India.svg',
            'address' => 'Plot No. C-38/39, Parinee Crescenzo, G-Block, 12th Floor, Bandra Kurla Complex, Bandra East, Taluka-Andheri, Mumbai - 400051, Maharashtra.',
            'email' => 'infodelhi@oisservices.com',
            'phone' => '+91 8800530119',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'India',
            'city' => 'New Delhi',
            'key' => '',
            'flag' => 'India.svg',
            'address' => 'C/O Central Board of Irrigation & Power Plot No. 4, Ground Floor, Institutional Area, Malcha Marg, Chanakyapuri New Delhi-110021',
            'email' => 'infodelhi@oisservices.com',
            'phone' => '+91 8800530119',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 4:30 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'USA',
            'city' => 'New York',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => 'OIS New York, 370 Lexington Ave, Suite 613 New York, NY 10017.',
            'email' => 'infony@oisservices.com',
            'phone' => '(+1)917-900-1114',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'France',
            'city' => 'Paris',
            'key' => 'PARIS',
            'flag' => 'France.svg',
            'address' => '9 Rue Paul Valery 75116 Paris, France',
            'email' => 'infoparis@oisservices.com',
            'phone' => '+33 1 83 92 77 81',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'South Africa',
            'city' => 'Pretoria',
            'key' => '',
            'flag' => 'SouthAfrica.svg',
            'address' => '3rd Floor, Building 2 Brooklyn Bridge Office Park Pretoria, 570 Fehrsen South Africa',
            'email' => 'infopret@oisservices.com',
            'phone' => '0270124336314',
            'working_time' => '9:00 am - 12:00 pm & 1:30 pm - 4:40 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Italy',
            'city' => 'Rome',
            'key' => 'ROME',
            'flag' => 'Italy.svg',
            'address' => 'Solutions S.R.L., Via Sicilia, 30 00187 Rome, Italy',
            'email' => 'inforome@oisservices.com',
            'phone' => '+39 (0)6 4201 2121',
            'working_time' => '9:30 am - 12:30 pm & 2:00 pm - 3:30 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'China',
            'city' => 'Shanghai',
            'key' => 'SHANGHAI',
            'flag' => 'China.svg',
            'address' => 'Room 506A, Zhongguancun Science Building, No.2911 North Zhongshan Road, Putuo',
            'email' => 'infoshanghai@oisservices.com',
            'phone' => '+86-2161670991',
            'working_time' => '9:00 am -  4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'USA',
            'city' => 'Washington DC',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => 'OIS WASHINGTON DC, 11900 Parklawn Drive Suite 160, Rockville MD 20852.',
            'email' => 'infowashingtondc@oisservices.com',
            'phone' => '(+1) 301-231-7000',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Germany',
            'city' => 'Berlin',
            'key' => '',
            'flag' => 'Germany.svg',
            'address' => 'Warmensteinacherstraße Straße 59 a, 12349 Berlin, Germany',
            'email' => 'N.A',
            'phone' => 'N.A',
            'working_time' => 'N.A',
            'working_days' => 'N.A',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Morocco',
            'city' => 'Rabat',
            'key' => '',
            'flag' => '',
            'address' => 'Millennium Business Centre, Av. Mehdi Ben Barka, Rabat 10170. Morocco',
            'email' => 'N.A',
            'phone' => 'N.A',
            'working_time' => 'N.A',
            'working_days' => 'N.A',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Turkey',
            'city' => 'Istanbul',
            'key' => '',
            'flag' => 'Turkey.svg',
            'address' => 'OIS Istanbul Sahrayıcedit Mahallesi, Atatürk Caddesi, Onur İş Merkezi, B Blok, No:3/7 Kadıköy/İstanbul',
            'email' => 'infoistanbul@oisservices.com',
            'phone' => '009 0216 385 79 41',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'UK',
            'city' => 'Manchester',
            'key' => '',
            'flag' => 'UK.svg',
            'address' => 'OIS SERVICES Regus ST JAMES TOWER 7 Charlotte Street Manchester M1 4DZ United Kingdom ',
            'email' => 'infomanchester@oisservices.com',
            'phone' => 'N.A',
            'working_time' => '9:00 am - 12:00 pm & 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Germany',
            'city' => 'Frankfurt',
            'key' => '',
            'flag' => 'Germany.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Hungary',
            'city' => 'Budapest',
            'key' => '',
            'flag' => 'Hungary.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Ireland',
            'city' => 'Dublin',
            'key' => '',
            'flag' => 'Ireland.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Belgium',
            'city' => 'Brussels',
            'key' => '',
            'flag' => 'Belgium.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Sweden',
            'city' => 'Stockholm',
            'key' => '',
            'flag' => 'Sweden.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Austria',
            'city' => 'Vienna',
            'key' => '',
            'flag' => 'Austria.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Romania',
            'city' => 'Bucharest',
            'key' => '',
            'flag' => 'Romania.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Poland',
            'city' => 'Warsaw',
            'key' => '',
            'flag' => 'Poland.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Portugal',
            'city' => 'Lisbon',
            'key' => '',
            'flag' => 'Portugal.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Greece',
            'city' => 'Athens',
            'key' => '',
            'flag' => 'Greece.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Cyprus',
            'city' => 'Nicosia',
            'key' => '',
            'flag' => 'Cyprus.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Switzerland',
            'city' => 'Bern',
            'key' => '',
            'flag' => 'Switzerland.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Qatar',
            'city' => 'Doha',
            'key' => '',
            'flag' => 'Qatar.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Japan',
            'city' => 'Tokyo',
            'key' => '',
            'flag' => 'Japan.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'South Korea',
            'city' => 'Seoul',
            'key' => '',
            'flag' => 'SouthKorea.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Thailand',
            'city' => 'Bangkok',
            'key' => '',
            'flag' => 'Thailand.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Hong Kong',
            'city' => 'Hong Kong',
            'key' => '',
            'flag' => 'HongKong.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Singapore',
            'city' => 'Singapore',
            'key' => '',
            'flag' => 'Singapore.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Australia',
            'city' => 'Canberra',
            'key' => '',
            'flag' => 'Australia.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Brazil',
            'city' => 'Brasilia',
            'key' => '',
            'flag' => 'Brazil.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Jamaica',
            'city' => 'Kingston',
            'key' => '',
            'flag' => 'Jamaica.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Uganda',
            'city' => 'Kampala',
            'key' => '',
            'flag' => 'Uganda.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Sudan',
            'city' => 'Khartoum',
            'key' => '',
            'flag' => 'Sudan.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Pakistan',
            'city' => 'Islamabad',
            'key' => '',
            'flag' => 'Pakistan.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Russia',
            'city' => 'Moscow',
            'key' => '',
            'flag' => 'Russia.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Senegal',
            'city' => 'Dakar',
            'key' => '',
            'flag' => 'Senegal.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Saudi Arabia',
            'city' => 'Riyadh, Jeddah and Makkah',
            'key' => '',
            'flag' => 'SaudiArabia.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'USA',
            'city' => 'Minneapolis',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Canada',
            'city' => 'Ottawa',
            'key' => '',
            'flag' => 'Canada.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Mauritius',
            'city' => 'Port Louis',
            'key' => '',
            'flag' => 'Mauritius.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Australia',
            'city' => 'Sidney',
            'key' => '',
            'flag' => 'Australia.svg',
            'address' => 'COMING SOON….!',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
    }
}
